### ISSUE TITLE
UnicodeDecodeError with default ascii encoding

### ISSUE THREAD

**Issue by thomashenauer** [xesscorp/KiField#1]
I have a "μ" in my part description and this caused KiField to fail with following error: 

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 14: ordinal not in range(128)

I fixed this by adding following lines in kifield.py:

> reload(sys)
> sys.setdefaultencoding('utf8')

I understand the setdefaultencoding() usage is not encouraged and the reload of sys is a workaround. But in the end it worked for me. See following link: http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

I use python 2.7 and KiField 0.1.1 on OS X 10.11.3

**Comment by DefProc** [comment]
I hit this problem too from using `µ` symbols in the schematic. While it looks like the default format for the schematic files is utf8, I at least got round the problem by running: 

`grep --color='auto' -P -n "[\x80-\xFF]" my_schematic.sch` 

([source](http://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix#9395552))

And replacing all the `µ` symbols with `u`

**Comment by kasbah** [comment]
Seems like you could also use Python 3 to avoid this error for the time being.
