### ISSUE TITLE
Issue after updating sch file from a XSLX containing cells with \n or \r chars

### ISSUE THREAD

**Issue by cvgaviao** [xesscorp/KiField#24]
I've exported the schematic to a XSLX file and added a description field to it.
I've copy and paste the descriptions from a web page. Some special invisible character have came in this operation.
In the component below the description line was broken into two lines. Kicad is no opening such file properly. I had to open the file in gedit and remove the new line one by one. 
```
    $Comp
    L TPS61291DRV U9
    U 1 1 588B46AE
    P 3930 3890
    F 0 "U9" H 3990 4710 60 0000 C CNN
    F 1 "TPS61291DRV" H 3990 4610 60 0000 C CNN
    F 2 "C8Tech_Power:DRV0006A" H -3770 -220 60 0001 C CNN
    F 3 "" H -3770 -160 60 0000 C CNN
    F 4 "LOW Iq BOOST CONVERTER WITH BYPASS OPERATION,
DRV0006A" H 0 0 50 0001 C CNN "description"
    F 5 "TPS61291DRV" H 0 0 50 0001 C CNN "mnp"
    F 6 "Texas Instruments" H 0 0 50 0001 C CNN "vendor"
	1    3930 3890
	1    0    0    -1  
    $EndComp
```

**Comment by xesscorp** [comment]
Apologies for the delay. This problem should be fixed.
