### ISSUE TITLE
Eagle support?

### ISSUE THREAD

**Issue by kasbah** [xesscorp/KiField#30]
I have been wondering whether a similar solution exists for Eagle. I stumbled on your [old ULPs](https://github.com/xesscorp/Eagle_PCB/tree/master/xess_ulp) and an [old tutorial of yours on making Eagle BOMs](http://www.xess.com/static/media/oss/tool_bom_03072011.php) but I couldn't find anything about "back importing" the attributes into the schematic. I have done some searching and no-one seems to be doing it. I haven't used Eagle enough to know, would it simply break the `.sch`/`.brd` if attributes were inserted?

**Comment by xesscorp** [comment]
I don't really know. Any work I did with Eagle was  pre-V6 before they moved to using text files.
