### ISSUE TITLE
Couldn't find a setup script

### ISSUE THREAD

**Issue by macsimski** [xesscorp/KiField#33]
After doing

`sudo easy_install kifield I get the error:`

error: Couldn't find a setup script in /home/simon/Documents/kicad/00tools/KiField/kifield

I have no experience with easy_install

**Comment by kasbah** [comment]
Have you tried `pip`? I am guessing you are using Debian/Ubuntu so it would be:

```
sudo apt install python3-pip
pip3 install kifield
```

**Comment by macsimski** [comment]
jep sudo pip install kifield did it. maybe elaborate on that in the readme. not everyone is savvy with python.
