### ISSUE TITLE
multiple issues with generated xlsx file; fields are very wrong

### ISSUE THREAD

**Issue by ppelleti** [xesscorp/KiField#34]
I generated an .xlsx file with the following command:

```
kifield -x Rgb7Hat.sch -i Rgb7Hat.xlsx -g -r
```

It has the following issues:

* The "mpn" and "description" columns are missing.
* The "footprint" column often contains the value of the "description" field instead of the value of the "footprint" field.
* There is an extra column named "60".
* FID2-FID6 entries are missing.

[kifield-trouble.zip](https://github.com/xesscorp/KiField/files/1399694/kifield-trouble.zip)

I'm using KiField 0.1.7 on Mac OS X 10.9.5.

**Comment by xesscorp** [comment]
Thanks for the detailed error report. The problem was caused by mishandling of escaped quotation marks inside a quoted string. Fixed in kifield 0.1.9.
