### ISSUE TITLE
Docs on installation are missleading

### ISSUE THREAD

**Issue by KarlZeilhofer** [xesscorp/KiField#42]
Hi, 

I've just installed kifield on Linux Mint 18.1 by running `$ sudo easy_install .`

Your docs says
`$ easy_install kifield`

Either this should be case sensitive  
`$ easy_install KiField`
or running from within the repos folder with  
`$ easy_install .`

Further more, a `sudo` is needed on Linux. 

Greets, Karl

**Comment by kasbah** [comment]
I think it would make more sense to recommend `pip` over `easy_install` anyway. https://packaging.python.org/guides/tool-recommendations/#id2
