### ISSUE TITLE
Trouble with Python3/basestring and None values.

### ISSUE THREAD

**Issue by poleguy** [xesscorp/KiField#52]
I had to hack in a few things to get kifield.py to work for me under anaconda python3.
one was:
```
    if USING_PYTHON2:
        bstr = basestring
    else:
        bstr = str
    if isinstance(collapsed, bstr):
```
Instead of 

```
    if isintance(collapsed, str) or isinstance(collapsed, basestring):
```

The other was adding a line to strip None:
```    
    possibilities = [x for x in possibilities if x is not None]
```
Just after def lc_get_close_matches(...)
Because it was crashing on str.lower a few lines lower when it hit any None values.

These are total hacks of course, but they got me going. I hope someone finds this useful.

**Comment by xesscorp** [comment]
I implemented your fixes. Thanks for the help!
