### ISSUE TITLE
fails to run with openpyxl 2.6.0, "has no attribute 'column_index_from_string'"'

### ISSUE THREAD

**Issue by hraftery** [xesscorp/KiField#53]
Seems issue #3 has reared its head again. Haven't seen the fix documented anywhere, so here goes.

kifield depends on openpyxl >= 2.3.2, however installing kifield fresh (this week, on Windows and macos) installs the latest version (v2.6.0). kifield then fails to run with error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 765, in insert_part_fields_into_wb
>     for h in headers}
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 765, in <dictcomp>
>     for h in headers}
>   File "/usr/local/lib/python3.7/site-packages/openpyxl/utils/cell.py", line 123, in column_index_from_string
>     return _COL_STRING_CACHE[str_col.upper()]
> AttributeError: 'int' object has no attribute 'upper'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/kifield3", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/kifield/__main__.py", line 148, in main
>     backup = not args.nobackup)
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 1219, in kifield
>     insert_part_fields(part_fields_dict, insert_filenames, recurse, group_components, backup)
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 1203, in insert_part_fields
>     insertion_functions[f_extension](part_fields_dict, f, recurse, group_components, backup)
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 880, in insert_part_fields_into_csv
>     wb = insert_part_fields_into_wb(part_fields_dict, wb)
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 768, in insert_part_fields_into_wb
>     for h in headers}
>   File "/usr/local/lib/python3.7/site-packages/kifield/kifield.py", line 768, in <dictcomp>
>     for h in headers}
> AttributeError: module 'openpyxl.cell' has no attribute 'column_index_from_string'
> 

A workaround is to force install a previous version (credit to @joshberryhooves for the fix) :

```
pip uninstall openpyxl
pip install openpyxl==2.3.2
```

**Comment by xesscorp** [comment]
KiField 0.1.15 fixes this problem caused by recent modifications to openpyxl. Make sure to upgrade your openpyxl to 2.6.0.
