### ISSUE TITLE
[KiField Bug] Missing dependency sexpdata for pip install

### ISSUE THREAD

**Issue by scandey** [xesscorp/KiField#67]
**Describe the bug**

After a clean install of Kifield 0.1.18 via Pip, first attempt at extracting from Kicad 5.1.10 schematic throws ModuleNotFoundError. This issue is new since 0.1.17.

**To Reproduce**
1. Attempt to extract a Kicad 5.1.10 schematic to .csv or .xlsx
2. See error

> Traceback (most recent call last):
  File "/usr/local/bin/kifield", line 5, in <module>
    from kifield.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/kifield/__main__.py", line 15, in <module>
    from .kifield import *
  File "/usr/local/lib/python3.9/site-packages/kifield/kifield.py", line 22, in <module>
    from .sch import Schematic, Schematic_V6
  File "/usr/local/lib/python3.9/site-packages/kifield/sch.py", line 16, in <module>
    import sexpdata
ModuleNotFoundError: No module named 'sexpdata'

**Expected behavior**

Schematic should be quietly extracted. 

**Desktop (please complete the following information):**
 - OS: Mac OS 11.3 
 - Python version: Python 3.9.5
 - KiField version: 0.1.18
 - KiCad version: 5.1.10_10_14

**Additional context**

After installing sexpdata via Pip separately, the extraction process continues to another unrelated error (NameError: name 'reduce' is not defined).

**Comment by xesscorp** [comment]
Oops. Thanks for finding that. At least it's easy to fix.
